name: INCEPTS
url: https://www.cmu.edu/energy/incepts/

exclude: [bibble, README.md, Makefile, screenshot.png]

# colorize code snippets with the pygments module
highlighter: pygments

# The path structure for blog posts.
permalink: /blog/:year/:month/:day/:title.html

# Sections on the "people" page.
roles:
  - key: member
    name:

# Number of news stories on the front page.
front_page_news: 8

# Base pathname for links.
baseurl: ""

# make pages for the _projects folder
collections:
  projects:
    output: true

# Navigation bar links.
navigation:
  - title: Home
    link: index.html
#  - title: Trip Planning
#    link: tripplanning.html
#  - title: Fleet Analysis
#    link: fleetanalysis.html
#  - title: Charger Placement
#    link: chargerplacement.html
  - title: Team
    link: index.html#people
  - title: News
    link: index.html#news
  - title: Publications
    link: publications.html
