name: CI
on: push

jobs:
  test:
    name: Check Links
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3
      - run: gem install jekyll html-proofer
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: pip install bibble
      - run: make build
      - run: make test
